### ISSUE TITLE
The postcode search returns addresses that aren't in order

### ISSUE THREAD

**Issue by joelanman** [alphagov/ier-frontend#1]
When you enter a postcode for the address step, the next screen has a <select> with a list of addresses. This list is not in a natural sort order, so eg. in a search for N11TY, Flat 109 comes before Flat 11.

[http://blog.codinghorror.com/sorting-for-humans-natural-sort-order/](http://blog.codinghorror.com/sorting-for-humans-natural-sort-order/)

This can make it very hard to find your address in the list.

**Comment by michaeldfallen** [comment]
:+1: but is this a bug in this repo or in [locate](https://github.com/alphagov/locate-api)?

IER Frontend relies upon the ordering locate returns addresses in. On one hand IER should present good ordering no matter, on the other hand if other sites use locate (do they?) you can kill two birds.

Depends where you want to solve it.
